### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Pantyhose-X** [LTCatt/PCL2Help#1]
直接导出成Minetest地图格式。有这个功能，你将获得太量国外用户。
https://forum.minetest.net/viewtopic.php?f=12&t=13709
https://forum.minetest.net/viewtopic.php?f=14&t=14271

**Comment by ExecuteIF** [comment]
捕获手写用户x1
![图片](https://user-images.githubusercontent.com/68136140/112836435-2cd84b00-90cd-11eb-8598-4f60b5e6e9fe.png)

**Comment by ChengT-cmd** [comment]
想法不错，但是至于这么做之后的影响会怎么样...
（希望没问题，但是不排除某些可能）

**Comment by ExecuteIF** [comment]
Why not use "discussions" /:

**Comment by ChengT-cmd** [comment]
但是Minetest与Minecraft真的有那么大的关系，值得在任何一个Minecraft启动器内进行互相转换吗

**Comment by shcdb** [comment]
一个mc启动器真的(哪怕)需要支持mt到mc存档互转吗

**Comment by LTCatt** [comment]
这是 PCL2 帮助的存储库，仅限讨论帮助相关的部分……**如果要提交 PCL2 本体的建议，请在反馈页面提交。**
此外，正如其他人所说，作为一个**启动器**，PCL2 没有必要加入这种过于跑题的功能……
