### ISSUE TITLE
PCL2内的使用 “VSCode获取帮助库”无法打开，但是从github上fork的帮助库是正常的

### ISSUE THREAD

**Issue by bling-yshs** [LTCatt/PCL2Help#108]

**Comment by WTP016-CN** [comment]
简单来说，就是 Github 更新了，PCL2 里面的没更新，或者是你 Fork 在 Help 文件夹里的没更新

**Comment by bling-yshs** [comment]
> 简单来说，就是 Github 更新了，PCL2 里面的没更新，或者是你 Fork 在 Help 文件夹里的没更新

所以我发issue

**Comment by LTCatt** [comment]
PCL2 的 Bug（

**Comment by LTCatt** [comment]
啊不对，是帮助库还没更新……
