### ISSUE TITLE
添加帮助页面刷新功能

### ISSUE THREAD

**Issue by NotKiller233** [LTCatt/PCL2Help#11]
在写帮助页面的时候总是要反复刷新页面，如果有语法错误还要重新启动PCL2。所以。。。能不能增加一个刷新帮助列表和内容的按钮= =

**Comment by NotKiller233** [comment]
这个功能可以放在高级设置给Autuor们使用= =

**Comment by 6get-xiaofan** [comment]
> 这个功能可以放在高级设置给Autuor们使用= =

这个功能有啊，鼠标悬停即可查看
![image](https://user-images.githubusercontent.com/57002549/113501379-32171900-9557-11eb-8f94-a6e1818f1d89.png)

**Comment by 6get-xiaofan** [comment]
个人认为没啥必要，毕竟就点一下刷新按钮，不用退出重进，这个功能有点累赘

**Comment by LTCatt** [comment]
语法错误不需要重新启动 PCL2 吧？如果有的话给点详细信息补充？
如果确实不需要重启的话，我觉得刷新按钮足够了。

**Comment by NotKiller233** [comment]
啊这之前确实没有注意到有刷新按钮= =
语法错误更正后刷新帮助页面确实不用重启
