### ISSUE TITLE
添加刷新帮助页面的快捷键

### ISSUE THREAD

**Issue by Misaka-L** [LTCatt/PCL2Help#15]
在修改帮助页面的布局的时候，需要经常刷新帮助页面。
把鼠标移到刷新按钮的操作比较耗时，可以添加一个快捷键比如 Ctrl+R 来快速刷新帮助。

**Comment by NotKiller233** [comment]
把数鼠标DPI调高点你就不觉得耗时了（雾

**Comment by LTCatt** [comment]
没啥必要……主要是写起来麻烦（run
PCL2 现在读帮助页面还是需要整体刷新的，单在子页面刷新可能会出奇怪的问题 Orz
