### ISSUE TITLE
1.12.2没有声音

### ISSUE THREAD

**Issue by HarryNiu** [LTCatt/PCL2Help#160]
我知道严格意义上这应该用启动器内置的反馈功能汇报，但我发誓我找不到那个按钮。。。。如果需要的话，请告诉我按钮在哪里，我会重新提交的。。。。

PCL2版本：2.2.14正式版

具体问题：

任何基于1.12.2版本的游戏都没有任何声音(但根据游戏内字幕，可以确定应该有声音)，是否安装Optifine和Forge，以及安装的mod不影响此bug的出现。

鉴于使用CurseForge官方app下载的1.12.2版本游戏和使用PCL2安装的其他所有版本(包括1.18.2以及数个1.16.5和1.7.2的模组包)都没有此音频问题，个人认为是个bug。

目前尝试过使用F3+S和F3+T来强制刷新游戏资源；重新下载游戏文件；调整游戏内音频参数；以及修改windows声音配置，均无法解决问题。

根据外网资料，本bug似乎可以通过在原版启动器生成的.minecraft/resource路径下添加一些音频文件解决，但该路径似乎不存在于本启动器生成的.minecraft路径下，故无法尝试。(注，已尝试过将文件放入version/版本名/resourcespacks 下，没有解决问题)

bug重现方式：创建新的1.12.2游戏文件，随后打开

崩溃报告：游戏除声音外运行正常，不会崩溃。如果有需要的话可以提交运行报告

**Comment by zkitefly** [comment]
**1.内置的反馈功能需要赞助后使用内测版才能出现**

2.可以尝试点击”补全文件“按钮

![image](https://user-images.githubusercontent.com/64117916/170805084-df73caba-c173-4986-9a63-cd992bf21ba4.png)

**Comment by HarryNiu** [comment]
感谢帮助，不过“补全文件”并没有解决此问题，目前已在反馈功能中重新提交。
