### ISSUE TITLE
一个小小的建议

### ISSUE THREAD

**Issue by hejingtong** [LTCatt/PCL2Help#162]
希望pcl2启动器的mod下载功能可以添加更多mod下载渠道。如我的世界中文下载站，我的世界中文论坛等。原因：有时在寻找某些特定mod时会出现”无搜索结果“。

**Comment by Big-Cake-jpg** [comment]
本仓库只受理 PCL2 帮助库相关问题，其余建议请前往反馈页面进行反馈
