### ISSUE TITLE
导入Forge整合包相关问题

### ISSUE THREAD

**Issue by Mondrian1337** [LTCatt/PCL2Help#168]
在导入CF整合包时，PCL2不会为整合包安装最新的Forge稳定版，导致使用Java8.0.333的用户无法正常启动整合包
![QQ截图20220628142622](https://user-images.githubusercontent.com/101363178/176108188-bb559295-b1f6-4db5-94ed-dfef3a99f6de.png)

**Comment by LTCatt** [comment]
整合包版本是由整合包作者提供的。
再说这是 PCL2 帮助库的……
