### ISSUE TITLE
规范化及可溯源性 的建议

### ISSUE THREAD

**Issue by 6get-xiaofan** [LTCatt/PCL2Help#17]
帮助库更应该像“百度百科”、“维基百科”等的**规范性及可溯源性**等的方面看齐，建议在帮助库添加 **<编写规范>** 帮助条目，规范一些内容，如：

- 某帮助条目的创建人及后续编辑者应在帮助页面**最下方**用警告框写出【File by xxx, Change by xxx】，不是写在最上方的。
- 某帮助条目的数据性资料或有关内容应该添加溯源信息可供查阅，像某些说明官方已经解释过的可以引用的同时添加源信息。
- 帮助条目的Title、Description等应该规范化：Title应该用简明骇要的概括内容，Description要在标题基础上包括关键词信息提供搜索准确查找结果，内容不大于25字。
- 帮助条目的编写应该使用 **第三方人称** 用 **官方** 的形式 **准确详细的** 编写，否则帮助库内容过于 **语言口语化、简单** 过及出现 **“智商高”** 的问题，将不利于 帮助库的发展！

此问题应该是每位参与编写的用户需要规范的内容，如果可以，我建议PCL2检测PCL目录下存在Help文件夹时的第一次启动，就强制打开编写规范，让编写者能了解到正确的编写规则，可以规范的编写相关内容！防止发展后期大量低质帮助充斥合并请求，导致的代码审查效率低慢！

**Comment by LTCatt** [comment]
在 帮助/提交帮助 中已经追加了规范性说明 :D
