### ISSUE TITLE
“自定义主页与帮助 XAML 格式”存在问题

### ISSUE THREAD

**Issue by Light-Beacon** [LTCatt/PCL2Help#20]
## Bug概述
前言的按钮“打开本篇的代码”点了报错：
![image](https://user-images.githubusercontent.com/49828867/114312076-ee5a7b80-9b23-11eb-85a2-1a0089de5fcc.png)
其原因是打开本地不存在的文件“\Help\个性化\XAML 格式.xaml”。
## 个人想到的解决方案
1.PCL2生成该文件
2.复制到剪贴板
@6get-xiaofan

**Comment by 6get-xiaofan** [comment]
我个人电脑可以打开，不知道此问题的具体原因

**Comment by LTCatt** [comment]
出现这一问题的原因是普通用户并没有 Clone 帮助库，他们的 Help 文件夹下是空的……
我不认为有啥处理这个 Bug 的好方法 :(
或许应该直接引导使用设置里的生成教学文件按钮……

**Comment by 6get-xiaofan** [comment]
@LTCatt  此文件既然可以在帮助库中查看，那么文件也一定存在，而 EventData 编写目录会默认将根目录选择为 PCL 文件夹，我检查代码时发现并没有任何错误，这是一个Bug，我创建全新文件夹尝试复现，但这根本不存在于“普通用户并没有 Clone 帮助库”的条件下，因为普通用户打开后的样子是这样的
![image](https://user-images.githubusercontent.com/57002549/115023206-0b5ec800-9ef1-11eb-8142-1bed37cf4af8.png)

所以，复现这个Bug的前提是 Clone  @帮助库了，请你 @Light-Beacon  检查你有没有将 “个性化\XAML 格式.xaml” 移动或者重命名。

**Comment by Light-Beacon** [comment]
@6get-xiaofan 帮助是内嵌在PCL2里边的，不会生成任何文件，我也从来没有 Clone 过帮助库，所以“个性化\XAML 格式.xaml”这个文件从来就没被生成，我自然也不可能移动和重命名。

**Comment by 6get-xiaofan** [comment]
“个性化\XAML 格式.xaml”此文件，就是你打开的这个文件，你既然在帮助库中打开了此文件，就代表此文件已经存在于“个性化”文件夹下，否则将无法打开这篇帮助，你也将无法点击此按钮

**Comment by Light-Beacon** [comment]
@6get-xiaofan  帮助一共有两个来源，一个**是PCL2自带的（内嵌）**，一个是**Help文件夹下的（自己写的）**，在这里提交的帮助都会**内嵌**，并不会生成在Help文件夹下。

**Comment by 6get-xiaofan** [comment]
OK，已想到解决方案！

**Comment by NotKiller233** [comment]
PCL2在启动的时候会把Github仓库下载到缓存文件夹= =在PCL/Help内有.helpignore文件才会把帮助页面替换为自定义帮助库。
所以如果是从未更改过自定义帮助库，那么有可能是帮助文件本身有问题。
