### ISSUE TITLE
似乎有人在侮辱PCL2

### ISSUE THREAD

**Issue by Jack253-png** [LTCatt/PCL2Help#215]
github : https://github.com/UnlegitMC/FuckPCL

README.MD : 
FuckPCL
A library to detect PCL(Plain Craft Launcher)

Why trying to block it
It just a launcher and it EVEN needs to pay to unload full features!
But they called "sponsor" but we think this NOT simple sponsor it JUST pay.
This the reason of we're creating this lib

Use
If your project are on kotlin

import com.guimc.fuckpcl.PCLChecker
PCLChecker.fullCheck(Minecraft.getMinecraft().mcDataDir/*, true*/) // boolean
If your project are on java

import com.guimc.fuckpcl.PCLChecker;
PCLChecker.INSTANCE.fullCheck(Minecraft.getMinecraft().mcDataDir/*, true*/);

**Comment by Big-Cake-jpg** [comment]
本仓库仅限对 PCL2 帮助库的讨论。

这边建议你直接私信龙腾猫跃

**Comment by LTCatt** [comment]
这是他们的个人行为，我管不动……

**Comment by Jack253-png** [comment]
所以还是尽快开源吧，hmcl没有给任何人骂过，因为所有快照版和测试版都是免费公开的...



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月02日 18:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [LTCatt/PCL2Help] 似乎有人在侮辱PCL2 (Issue #215) |

这是他们的个人行为，我管不动……

**Comment by z0z0r4** [comment]
没有任何实质性价值的issue，除了不必要增加压力

> 所以还是尽快开源吧，hmcl没有给任何人骂过，因为所有快照版和测试版都是免费公开的... | | ***@***.*** | | ***@***.*** |
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年08月02日 18:57 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.******@***.***> | | 主题 | Re: [LTCatt/PCL2Help] 似乎有人在侮辱PCL2 (Issue #215) | 这是他们的个人行为，我管不动…… — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>
