### ISSUE TITLE
申请 collaborator 

### ISSUE THREAD

**Issue by 6get-xiaofan** [LTCatt/PCL2Help#23]
我想申请 PCL帮助库 的 collaborator ，我对 Github 较为了解，且时间充裕，会认真负责审核每一段代码。

**Comment by ImFunnySun** [comment]
应该要提交代码并且成功被合并才能获得吧、(maybe)

**Comment by ImFunnySun** [comment]
![image](https://user-images.githubusercontent.com/68582223/115039279-e4a98d00-9f02-11eb-8e83-d1fddefe65fc.png)
你本来就是啊

**Comment by LTCatt** [comment]
你本来就是啊.jpg
