### ISSUE TITLE
自定义帮助文件在pcl2自己清理缓存之后消失并导致错误

### ISSUE THREAD

**Issue by ShizhenZhou** [LTCatt/PCL2Help#237]
[Log1.txt](https://github.com/LTCatt/PCL2Help/files/9290680/Log1.txt)
![2022-08-09 (4)](https://user-images.githubusercontent.com/110872404/183653413-f68cc85d-dffa-456d-b864-23311cf065d7.png)
复现方法：生成教学文件→清理缓存（PCL2貌似会自己清理缓存，所以会不定时自发出现，很让人烦恼）
注：我已经将PCL2更新为最新版本

**Comment by Big-Cake-jpg** [comment]
https://github.com/Hex-Dragon/PCL2

去提个 Issue？这里基本不看的

**Comment by LTCatt** [comment]
PCL2 的 Issue 不在帮助库处理
