### ISSUE TITLE
Fabric错误后给出的解决方案显示不完全

### ISSUE THREAD

**Issue by AwardedStatue97** [LTCatt/PCL2Help#239]
![image](https://user-images.githubusercontent.com/101795180/185093258-dc263a0b-522a-447b-b062-284e5394c22c.png)
效果如上
复现步骤：将多个冲突的模组同时加载（如sodium和optifine）导致出错，再关闭窗口即可复现

**Comment by LTCatt** [comment]
这不是反馈 PCL2 本体问题的地方
