### ISSUE TITLE
关于pcl2 2.3.2.0Mod搜索界面发生错误

### ISSUE THREAD

**Issue by zjriss** [LTCatt/PCL2Help#241]
在pcl2 2.3.2.0、下载—Mod中，“搜索”功能失效。
![image](https://user-images.githubusercontent.com/110586510/185782959-5beb4c9d-aa5c-4466-81e1-dd9fa008b95f.png)
无论搜索界面输入什么，都是搜索失败。
与网络、网络环境无关，已测试。
版本为最新。

**Comment by Big-Cake-jpg** [comment]
这是帮助库，不受理 PCL2 反馈

**Comment by LTCatt** [comment]
PCL2 的 Issue 不在帮助库处理
