### ISSUE TITLE
关于PCL2启动器Mod下载未更新

### ISSUE THREAD

**Issue by YUANXINGlingyun** [LTCatt/PCL2Help#243]
Create（机械动力）已经支持1.19 但是无法在PCL启动器中找到
![image](https://user-images.githubusercontent.com/109946426/186122253-9da0b4e9-1b5d-47c2-b40c-4af97fbd12d6.png)

**Comment by LTCatt** [comment]
PCL2 的 Issue 不在帮助库处理
