### ISSUE TITLE
帮助库的联机常见问题中有误导萌新的地方

### ISSUE THREAD

**Issue by LTDove** [LTCatt/PCL2Help#244]
自定义局域网联机目前版本更新到了1.19.1这边需要更新一下（
![%LLEXSD5)1RX~@AVBIMFKY9](https://user-images.githubusercontent.com/107299327/186406542-42f72488-5bf1-425a-99ff-f01b1b34d76f.png)

**Comment by XieXiLin3** [comment]
小提示: 1.19.x
![image](https://user-images.githubusercontent.com/55585872/186441362-859c3c64-5809-471b-bd1f-06b2305bdc55.png)
