### ISSUE TITLE
PCL2错误

### ISSUE THREAD

**Issue by 152qq** [LTCatt/PCL2Help#251]
PCL2帮助错误，每次打开都有，群内管理要问你，帮助一下，谢谢了。
[pcl2错误.zip](https://github.com/LTCatt/PCL2Help/files/9720796/pcl2.zip)

**Comment by zkitefly** [comment]
你打开一下这个目录并截个图？

G:\mincraft\PCL\

**Comment by 152qq** [comment]
好

**Comment by 152qq** [comment]
![屏幕截图 2022-10-06 103805](https://user-images.githubusercontent.com/113680257/194206594-59c0ba9d-ccfa-4a94-b0ed-44b3b801a6ea.png)
![屏幕截图 2022-10-06 103919](https://user-images.githubusercontent.com/113680257/194206598-f7c3427c-7c7c-4564-81f7-767d45d8f405.png)
![屏幕截图 2022-10-06 103928](https://user-images.githubusercontent.com/113680257/194206600-cb3330a6-5f84-4ab5-aa31-cb15bcf9d766.png)
![屏幕截图 2022-10-06 103939](https://user-images.githubusercontent.com/113680257/194206605-e95d97e6-3384-4963-8240-08e087d6413a.png)
![屏幕截图 2022-10-06 103952](https://user-images.githubusercontent.com/113680257/194206607-67eac533-2eb1-4ab5-b360-1634ec46e101.png)
![屏幕截图 2022-10-06 104005](https://user-images.githubusercontent.com/113680257/194206611-c063ae39-43d2-4c31-81af-793f0b863d5b.png)
![屏幕截图 2022-10-06 104019](https://user-images.githubusercontent.com/113680257/194206614-a8e849cd-f9e4-4ba1-8a2a-e892125f83ea.png)
![屏幕截图 2022-10-06 103720](https://user-images.githubusercontent.com/113680257/194206590-b3505a32-ff3b-4cbd-8a87-0bc293cc9672.png)
![屏幕截图 2022-10-06 103753](https://user-images.githubusercontent.com/113680257/194206591-d95bb8d6-bfd6-4d65-a744-ac71a1b09b1c.png)

![屏幕截图 2022-10-06 104031](https://user-images.githubusercontent.com/113680257/194206617-f3c45673-af46-40ba-8661-4485063be855.png)
![屏幕截图 2022-10-06 104221](https://user-images.githubusercontent.com/113680257/194206619-605740ce-1414-4e86-9ac8-5b4333736d3c.png)
![屏幕截图 2022-10-06 104242](https://user-images.githubusercontent.com/113680257/194206623-d42743da-23a3-4d05-bd55-e3761c8f86b3.png)
![屏幕截图 2022-10-06 104259](https://user-images.githubusercontent.com/113680257/194206627-08d43aa6-b4e4-4661-b780-befe8cbc70fd.png)
![屏幕截图 2022-10-06 104359](https://user-images.githubusercontent.com/113680257/194206629-c8c2bf16-a371-4a54-b305-a8095cb56e25.png)
![屏幕截图 2022-10-06 104408](https://user-images.githubusercontent.com/113680257/194206631-db705a39-8d69-4b64-8b33-21401a2a060c.png)
![屏幕截图 2022-10-06 104418](https://user-images.githubusercontent.com/113680257/194206632-782fcafc-503c-4947-a9a5-ee7ab6bc2f6a.png)
![屏幕截图 2022-10-06 104432](https://user-images.githubusercontent.com/113680257/194206635-f3591d8a-65dd-4c35-8ae7-85bb1a80496e.png)
![屏幕截图 2022-10-06 104441](https://user-images.githubusercontent.com/113680257/194206638-3f723ee2-31c8-4a50-9abe-e59ead8fdb89.png)
![屏幕截图 2022-10-06 104450](https://user-images.githubusercontent.com/113680257/194206642-7ac624a6-a407-4f51-b4ab-02c85ffbdfea.png)
![屏幕截图 2022-10-06 104457](https://user-images.githubusercontent.com/113680257/194206646-23601c54-79af-4bd6-b58f-fae41b53e5fa.png)
![屏幕截图 2022-10-06 104506](https://user-images.githubusercontent.com/113680257/194206648-5b645807-d4c6-4452-b0ba-16ecc958656c.png)
![屏幕截图 2022-10-06 104516](https://user-images.githubusercontent.com/113680257/194206654-679c9348-c29d-4114-8da7-1535cf7369c8.png)
![屏幕截图 2022-10-06 104526](https://user-images.githubusercontent.com/113680257/194206655-b58b6ef5-4619-4278-a201-8794c0618b13.png)
![屏幕截图 2022-10-06 104534](https://user-images.githubusercontent.com/113680257/194206657-bb4845bb-1bf3-4602-b29f-57824162d08b.png)
![屏幕截图 2022-10-06 104609](https://user-images.githubusercontent.com/113680257/194206662-0a0bd57e-5065-4539-b603-ac5c0146b3e0.png)

**Comment by 152qq** [comment]
![image](https://user-images.githubusercontent.com/113680257/194207059-8423ecec-3100-4556-863a-5f52f512aef9.png)

**Comment by 152qq** [comment]
![image](https://user-images.githubusercontent.com/113680257/194207129-9180914d-a003-46b0-a49e-8f3b9f7324ee.png)

**Comment by 152qq** [comment]
![image](https://user-images.githubusercontent.com/113680257/194207594-0ba64fca-d0b9-4b44-a076-d6bd4200984e.png)

**Comment by zkitefly** [comment]
> 

随便点进去一个文件夹再截个图？

**Comment by zkitefly** [comment]
> ![image](https://user-images.githubusercontent.com/113680257/194207594-0ba64fca-d0b9-4b44-a076-d6bd4200984e.png)


随便点进去一个文件夹再截个图？

**Comment by 152qq** [comment]
![Screenshot_20221006_120127](https://user-images.githubusercontent.com/113680257/194211285-ecbf5cc1-4c17-49e4-b4a4-ea168153dfad.jpg)

**Comment by zkitefly** [comment]
emm，这很奇怪

**Comment by 152qq** [comment]
咋了

**Comment by 152qq** [comment]
删了重新下载也不行

**Comment by 152qq** [comment]
？

**Comment by z0z0r4** [comment]
建议前往 PCL2 仓库提交，这里与启动器代码无关，帮不了你

**Comment by z0z0r4** [comment]
https://github.com/Hex-Dragon/PCL2/issues/194

**Comment by LTCatt** [comment]
使用 https://github.com/Hex-Dragon/PCL2/issues/196
