### ISSUE TITLE
[BUG]愚人节快照版本 20w14∞ (20w14infinite) 版本无法选择安装 fabric loader，显示没有可用版本，但实际可装

### ISSUE THREAD

**Issue by LittleCircleOO** [LTCatt/PCL2Help#254]
### 复现步骤
1. 启动 PCL2，点击下载选项卡；
2. 选择 20w14∞ 愚人节版本；
### 预期结果
支持选择安装 Fabric 。
### 实际结果
Fabric 栏显示“没有可用版本”，无法安装。
![PCL2](https://user-images.githubusercontent.com/51949761/197461349-298e1dde-3ea9-4666-8bff-5d4a0d991d6e.png)
但实际上 Fabric 官方提供的安装器当中是支持 20w14∞ 快照的选择安装的。
![Fabric_Installer](https://user-images.githubusercontent.com/51949761/197461392-f1cea4b7-200e-4cf3-b5ef-18a20fb699b7.png)
### 当前版本
Snapshot 2.4.0 (266.0)

**Comment by Big-Cake-jpg** [comment]
此仓库不受理 PCL2 本体的反馈。请前往 Hex-Dragon/PCL2 仓库
