### ISSUE TITLE
更新 LittleSkin 外置登录教程

### ISSUE THREAD

**Issue by LTCatt** [LTCatt/PCL2Help#255]
![image](https://user-images.githubusercontent.com/40348278/201061233-5de909e8-2127-467c-a521-267ebbc96ff8.png)

该教程已经过时，现在有更快捷的方式进行设置：

![image](https://user-images.githubusercontent.com/40348278/201061337-1ae65549-8db9-4d58-a709-82eeb793ee17.png)

**Comment by WTP016-CN** [comment]
#258
