### ISSUE TITLE
图片加载失败

### ISSUE THREAD

**Issue by ExpertPbSeal** [LTCatt/PCL2Help#257]
“帮助”-“资源安装指南”-“安装资源包”-”对于1.16以上版本的安装方法”中最后一张图片显示“404 Not Found”，重启启动器、清理缓存后仍无法有效解决此问题。

*初步怀疑是图床链接失效

<img width="641" alt="屏幕截图 2022-11-18 194630" src="https://user-images.githubusercontent.com/79563897/202698285-3f8407fb-fbee-48f9-8298-5663a0a16fc6.png">

**Comment by WTP016-CN** [comment]
稍后解决

**Comment by WTP016-CN** [comment]
#258

**Comment by z0z0r4** [comment]
sorrrrrrrrrrrrrrry!
