### ISSUE TITLE
一些帮助页面的问题

### ISSUE THREAD

**Issue by NotKiller233** [LTCatt/PCL2Help#26]
在[https://github.com/LTCatt/PCL2Help/blob/master/%E5%B8%AE%E5%8A%A9/%E6%8F%90%E4%BA%A4%E5%B8%AE%E5%8A%A9%20-%20Git.xaml](https://github.com/LTCatt/PCL2Help/blob/master/%E5%B8%AE%E5%8A%A9/%E6%8F%90%E4%BA%A4%E5%B8%AE%E5%8A%A9%20-%20Git.xaml)中第63行含有误导性文字
https://github.com/settings/keys 是Github密钥管理界面，并不是设置界面

在[https://github.com/LTCatt/PCL2Help/blob/master/%E5%B8%AE%E5%8A%A9/%E6%8F%90%E4%BA%A4%E5%B8%AE%E5%8A%A9%20-%20Git.xaml](https://github.com/LTCatt/PCL2Help/blob/master/%E5%B8%AE%E5%8A%A9/%E6%8F%90%E4%BA%A4%E5%B8%AE%E5%8A%A9%20-%20Git.xaml)中第37行含有误导性文字
此操作只会生成SHA-256格式的SSH密钥，并不存在公钥与私钥的说法。

在[https://github.com/LTCatt/PCL2Help/blob/master/%E5%B8%AE%E5%8A%A9/%E6%8F%90%E4%BA%A4%E5%B8%AE%E5%8A%A9%20-%20Git.xaml](https://github.com/LTCatt/PCL2Help/blob/master/%E5%B8%AE%E5%8A%A9/%E6%8F%90%E4%BA%A4%E5%B8%AE%E5%8A%A9%20-%20Git.xaml)中第31行含有误导性文字
并不是使用过Git就不需要配置Github账号SSH密钥，Git并不是Github开发的软件，不需要连接Github账号也可以使用。
此外还有GitLab，Gitee等在线Git仓库也是一样的配置方法，不应过于绝对。

在[https://github.com/LTCatt/PCL2Help/blob/master/%E5%B8%AE%E5%8A%A9/%E6%8F%90%E4%BA%A4%E5%B8%AE%E5%8A%A9%20-%20Git.xaml](https://github.com/LTCatt/PCL2Help/blob/master/%E5%B8%AE%E5%8A%A9/%E6%8F%90%E4%BA%A4%E5%B8%AE%E5%8A%A9%20-%20Git.xaml)中第115，118行含有术语错误
应为拉取请求而不是合并请求

在[https://github.com/LTCatt/PCL2Help/blob/master/%E5%B8%AE%E5%8A%A9/%E7%BC%96%E5%86%99%E8%A7%84%E8%8C%83.xaml](https://github.com/LTCatt/PCL2Help/blob/master/%E5%B8%AE%E5%8A%A9/%E7%BC%96%E5%86%99%E8%A7%84%E8%8C%83.xaml)第100行有误导性文字
应为提交拉取请求而不是提交合并

在[https://github.com/LTCatt/PCL2Help/blob/master/%E5%B8%AE%E5%8A%A9/%E6%8F%90%E4%BA%A4%E5%B8%AE%E5%8A%A9%20-%20GitHub%20Desktop.xaml](https://github.com/LTCatt/PCL2Help/blob/master/%E5%B8%AE%E5%8A%A9/%E6%8F%90%E4%BA%A4%E5%B8%AE%E5%8A%A9%20-%20GitHub%20Desktop.xaml)第17行有符号错误

**Comment by 6get-xiaofan** [comment]
首先感谢你提出以上问题，下面做统一回复。

对于“https://github.com/settings/keys 是Github密钥管理界面，并不是设置界面”，我的解释是，它包含在设置页面以内，并不是独立页面，而“访问设置”中的“设置”是指访问后进行设置。

对于“此操作只会生成SHA-256格式的SSH密钥，并不存在公钥与私钥的说法。”，我的解释是，Git会生成公钥和私钥，id_rsa.pub是公钥，id_rsa是私钥，这点完全可以百度找得到。

对于“并不是使用过Git就不需要配置Github账号SSH密钥，Git并不是Github开发的软件，不需要连接Github账号也可以使用。
此外还有GitLab，Gitee等在线Git仓库也是一样的配置方法，不应过于绝对。”，我的解释是，我在编写时所撰写的“使用 Git 与 GitHub 账户建立连接”中的“建立连接”仅仅指它们之间可以通过某种传输协议达到其功能的目的；对于“此外还有GitLab，Gitee等在线Git仓库也是一样的配置方法，不应过于绝对。”我的解释是：我并没有撰写提及或绝对说明 GitLab、Gitee不能使用 的文字，且这不是教，怎么用Git获取帮助库并上传到GitLab or Gitee。

对于“应为提交拉取请求而不是提交合并”，我的解释是，官方并没有对“Pull Requests”此单词的官方中文释义，且中国Gitee也没有对此单词有过中文释义，严格来说要使用“Pull Requests”英文来撰写的，所以并不存在“误导性”，对于此问题我将在下个Pull Requests中修改。

对于“第17行有符号错误”，此问题我将不做解释，因为非我编写的内容。

**Comment by 6get-xiaofan** [comment]
补充：
对于“并不是使用过Git就不需要配置Github账号SSH密钥”，我的解释是，Git生成的密钥是储存在当前电脑账户下的文件夹内，当你将公钥与Github绑定后，所有关于此电脑账户下的任何仓库的推送都是可行的，折叠框内的即是对已完成密钥绑定用户的不必要内容。怀疑你有认真学习过Git吗？ #.#

此外建议你多写两篇帮助而不是纠结小问题，就算遇到小问题，如果是能解决，你可以 完善/修改 ，并不是在这里让我有一种“被挑刺”的感觉。

**Comment by NotKiller233** [comment]
Github账号生成的SSH密钥只能Github上用= =另外我确实是好好学习过Git的呢
Pull Requests在Git中文社区的翻译是拉取请求= =
另外Git只会生成SSH密钥确实我我记错了

**Comment by NotKiller233** [comment]
多写两篇帮助并不会有任何的好处= =因为这是从我写的帮助中分离出来的，擅自修改不一定会有更好的效果

**Comment by NotKiller233** [comment]
找出错误的原因是在编写规范里第41行中提到的“规范的文字和措辞”，并不是刻意挑剔= =

**Comment by NotKiller233** [comment]
> 对于“并不是使用过Git就不需要配置Github账号SSH密钥，Git并不是Github开发的软件，不需要连接Github账号也可以使用。
> 此外还有GitLab，Gitee等在线Git仓库也是一样的配置方法，不应过于绝对。”，我的解释是，我在编写时所撰写的“使用 Git 与 GitHub 账户建立连接”中的“建立连接”仅仅指它们之间可以通过某种传输协议达到其功能的目的；对于“此外还有GitLab，Gitee等在线Git仓库也是一样的配置方法，不应过于绝对。”我的解释是：我并没有撰写提及或绝对说明 GitLab、Gitee不能使用 的文字，且这不是教，怎么用Git获取帮助库并上传到GitLab or Gitee。

另外按照规范，中英文不应混用才对= =

**Comment by NotKiller233** [comment]
> 对于“并不是使用过Git就不需要配置Github账号SSH密钥，Git并不是Github开发的软件，不需要连接Github账号也可以使用。
> 此外还有GitLab，Gitee等在线Git仓库也是一样的配置方法，不应过于绝对。”，我的解释是，我在编写时所撰写的“使用 Git 与 GitHub 账户建立连接”中的“建立连接”仅仅指它们之间可以通过某种传输协议达到其功能的目的；对于“此外还有GitLab，Gitee等在线Git仓库也是一样的配置方法，不应过于绝对。”我的解释是：我并没有撰写提及或绝对说明 GitLab、Gitee不能使用 的文字，且这不是教，怎么用Git获取帮助库并上传到GitLab or Gitee。

此处你的原文是"对与此步骤在已使用过Git的用户是无需的查看的"，我认为这里有误导性文字，因为使用过Git的人不一定使用过Github

**Comment by NotKiller233** [comment]
另外拉取请求已经是Github官方翻译了
具体可以看这里[https://docs.github.com/cn/github/collaborating-with-issues-and-pull-requests/about-pull-requests](https://docs.github.com/cn/github/collaborating-with-issues-and-pull-requests/about-pull-requests)

**Comment by 6get-xiaofan** [comment]
以上问题我会解决，当然：

对于“另外按照规范，中英文不应混用才对= =”，我的解释是，此处在issues中讨论，并不是在帮助库中撰写，所以中英混用是可以的。

对于“使用过Git的人不一定使用过Github”的问题，我在下个Pull Requests中会改为“对于此步骤，在已使用过Git与Github建立过连接的用户，是无需的查看的”

对于“多写两篇帮助并不会有任何的好处= =因为这是从我写的帮助中分离出来的，擅自修改不一定会有更好的效果”，我的解释是，这本就是一个公益性的项目，谈何“好处”？你指的“分离出来的”，指哪些？你的修改是受到审核的，所以你大可放心的改。

现在我不会对此 issues 有任何回复，对于你的好的建议我会采纳，对于你的非可行性的建议恕我不予采纳，谢谢 : ）
