### ISSUE TITLE
[Backup] 对大图压缩的知会及备份

### ISSUE THREAD

**Issue by z0z0r4** [LTCatt/PCL2Help#261]
这是一份有关图床的统计数据
[1306226738-mainland-2022-09-22-2022-12-21_flux_top100_urls.xlsx](https://github.com/LTCatt/PCL2Help/files/10273842/1306226738-mainland-2022-09-22-2022-12-21_flux_top100_urls.xlsx)

https://cdn.img.z0z0r4.top/2022/07/26/6/minecraft-settings.png 
这张意义不大的图消耗了 10G 还是比较震撼的hhh
刚刚已经手动压缩了

细节见下图
![image](https://user-images.githubusercontent.com/78744121/208801142-aa4268fb-4bd5-45bf-b0a5-1ae8578dc86a.png)

**Comment by LTCatt** [comment]
umm 你可以直接压？

**Comment by z0z0r4** [comment]
> umm 你可以直接压？

压完了来知会一声而已...

**Comment by LTCatt** [comment]
……那可以 close 了？

**Comment by z0z0r4** [comment]
嘎的图我都会在这扔个备份
2022-12-28 https://cdn.img.z0z0r4.top/2022/11/19/6/littleskin-login.png
原图 3.46 MB (3,639,064 字节) -> 71.9 KB (73,633 字节)
![littleskin-login](https://user-images.githubusercontent.com/78744121/209785244-8fe36c02-f422-4819-a01b-f8202a6e264b.png)

**Comment by z0z0r4** [comment]
采用工具：[squoosh](https://squoosh.app/)
https://github.com/GoogleChromeLabs/squoosh

**Comment by LTCatt** [comment]
我加个 pin，没必要 open 着了（

**Comment by z0z0r4** [comment]
thx

**Comment by WTP016-CN** [comment]
> ## 嘎的图我都会在这扔个备份
> 
> 2022-12-28 https://cdn.img.z0z0r4.top/2022/11/19/6/littleskin-login.png 原图 3.46 MB (3,639,064 字节) -> 71.9 KB (73,633 字节) 202212-27 当日消耗
> cdn.img.z0z0r4.top/2022/11/19/6/littleskin-login.png 	414.91MB
> 
> ![littleskin-login](https://user-images.githubusercontent.com/78744121/209785244-8fe36c02-f422-4819-a01b-f8202a6e264b.png)

怪我
截图工具保存开了100%品质……

**Comment by z0z0r4** [comment]
> > ## 嘎的图我都会在这扔个备份
> > 2022-12-28 https://cdn.img.z0z0r4.top/2022/11/19/6/littleskin-login.png 原图 3.46 MB (3,639,064 字节) -> 71.9 KB (73,633 字节) 202212-27 当日消耗
> > cdn.img.z0z0r4.top/2022/11/19/6/littleskin-login.png 	414.91MB
> > ![littleskin-login](https://user-images.githubusercontent.com/78744121/209785244-8fe36c02-f422-4819-a01b-f8202a6e264b.png)
> 
> 怪我 截图工具保存开了100%品质……

截图工具不开100%画质，发图的时候会有更多人怪你的（

**Comment by z0z0r4** [comment]
https://gist.github.com/z0z0r4/03f9ccd72e50e92b93149d9547740121 分享点好东西
