### ISSUE TITLE
Readme 的头图炸了

### ISSUE THREAD

**Issue by LTCatt** [LTCatt/PCL2Help#284]
![image](https://user-images.githubusercontent.com/40348278/223727887-b27b95cb-2996-4e91-bf98-55d0b14dc4ae.png)

**Comment by RawDiamondMC** [comment]
正常显示？
![屏幕截图 2023-03-08 222906](https://user-images.githubusercontent.com/112449001/223739824-59b43a39-d02f-4531-994d-9ad00ddb51bc.png)

**Comment by WorldHim** [comment]
GitHub的锅，close吧。。
