### ISSUE TITLE
PCL II在有时安装MC预览发行版本安装后会间隔很长时间后才显示

### ISSUE THREAD

**Issue by a-047** [LTCatt/PCL2Help#295]
在有时安装MC预览发行版本安装后会间隔很长时间后才显示，不展示的概率没有统计，可能只是出现错误（概率极小）.

**Comment by LTCatt** [comment]
镜像源未更新，并非启动器问题

**Comment by a-047** [comment]
谢谢你给予我的意见，是我给你制作的头像还望喜欢。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年5月16日 4:31
收件人: ***@***.***>
抄送: ***@***.***>; State ***@***.***>
主题: Re: [LTCatt/PCL2Help] PCL II在有时安装MC预览发行版本安装后会间隔很长时间后才显示 (Issue #295)


镜像源未更新，并非启动器问题

―
