### ISSUE TITLE
更新时提示更新文件有潜在的病毒和垃圾文件

### ISSUE THREAD

**Issue by gyc0927** [LTCatt/PCL2Help#300]
![image](https://github.com/LTCatt/PCL2Help/assets/136293761/9791b71a-b4ea-4005-bb3b-0f38e34d3ed3)
更新时提示潜在的病毒和垃圾文件

**Comment by Hatsushigure** [comment]
这个是把 Windows Defender 的消息搬过来的，你在WD 里添加信任就行了
