### ISSUE TITLE
自定义帮助导致崩溃

### ISSUE THREAD

**Issue by z0z0r4** [LTCatt/PCL2Help#319]
将仓库当前的 `安装 Mod` 在启动器中加载就会卡死，不存在报错，直接崩溃...未能理解原因

**Comment by z0z0r4** [comment]
![image](https://github.com/LTCatt/PCL2Help/assets/78744121/e34319b1-3e64-4555-944a-140c69ea8edf)

**Comment by tangge233** [comment]
没能复现此问题。是不是图片加载太慢的问题？

**Comment by z0z0r4** [comment]
> 没能复现此问题。是不是图片加载太慢的问题？

应该不是…我这能稳定复现，怪

**Comment by LTCatt** [comment]
![image](https://github.com/LTCatt/PCL2Help/assets/40348278/39cbe1e3-13e3-4dd1-9f09-8a304be99a43)
我这也没问题……
如果还有人出现再说吧……
