### ISSUE TITLE
resources.cakeskin.tk 爆了

### ISSUE THREAD

**Issue by z0z0r4** [LTCatt/PCL2Help#320]
当初我换链接的时候没正则到这几张，所以没迁移到

bigcake 的存储桶已经没了，图片已丢失

![image](https://github.com/LTCatt/PCL2Help/assets/78744121/9d738b37-f44a-43c3-956b-fada33d9170f)

`ping: resources.cakeskin.tk: Name or service not known`

**Comment by Big-Cake-jpg** [comment]
蚌 我这就重新截几张图

**Comment by LTCatt** [comment]
已由 #321 修复
