### ISSUE TITLE
local:MyCard的属性Foreground无法正常识别

### ISSUE THREAD

**Issue by IambicCave** [LTCatt/PCL2Help#324]
1、警告页面如下：
![#1](https://github.com/LTCatt/PCL2Help/assets/79430466/169617b8-2916-4599-a722-bfe789d1e469)

2、Custom.xaml出错位置内容内容如下：
![#2](https://github.com/LTCatt/PCL2Help/assets/79430466/01d0be1f-d4a4-4353-b285-f9d4eea2a82a)

3、教学文件中关于local:MyCard的属性列举如下：
![#3](https://github.com/LTCatt/PCL2Help/assets/79430466/104bb2ee-c760-4e71-a2b5-4bf32a2890b0)

PCL2将local:MyCard的属性Foreground识别为“未知成员”，与教学文件不符。另外根据issue#256，其他gadget也许也会出现类似的问题。

**Comment by LTCatt** [comment]
教学文件内容有误，这玩意儿没有 Foreground 属性（

**Comment by IambicCave** [comment]
> 

蚌埠

**Comment by LTCatt** [comment]
诶你别 close 了啊，之后可以改教学文件 =。=
