### ISSUE TITLE
使用runespace的wiki

### ISSUE THREAD

**Issue by deep-dark-forest** [LTCatt/PCL2Help#330]
话说最近minecraft wiki不是快从fandom迁移到runespacewiki了吗，新域名是minecraft.wiki。runespacewiki的访问比fandom稳定得多，仅在极少数地区存在超时问题。bilibili的wiki更新速度很慢，都快差一个月了，我觉得可以同时保留两个按钮，一个bilibili的一个runespace的。

**Comment by deep-dark-forest** [comment]
可以点击[这里](https://www.bilibili.com/video/BV1XN411J7Ek/?spm_id_from=333.337.search-card.all.click)了解更多信息。还有就是，Runespace上的minecraft wiki目前只有英文版，不过中文版应该不会远了。

**Comment by JingHai-Lingyun** [comment]
不急 等中文适配先

**Comment by WForst-Breeze** [comment]
不急，等完全中文的迁移过去就会适配的，现在体验下来国内访问感觉速度不错，感觉可以代替更新较慢的bwiki了
