### ISSUE TITLE
Wiki 链接炸了

### ISSUE THREAD

**Issue by LTCatt** [LTCatt/PCL2Help#334]
#333 @WForst-Breeze

**Comment by WForst-Breeze** [comment]
> 当前中文百科尚未迁移，因此这个 pr 暂时不必合并。

（

**Comment by LTCatt** [comment]
是我没看 orz

**Comment by z0z0r4** [comment]
2333333

**Comment by JingHai-Lingyun** [comment]
搬了 https://www.bilibili.com/read/cv27629632/
地址是 https://zh.minecraft.wiki

**Comment by WForst-Breeze** [comment]
那那个链接就是可以用的

**Comment by JingHai-Lingyun** [comment]
#330 和这个可以关了
然后指定 Minecraft 版本的更新日志的Wiki链接有 Hex-Dragon/PCL2#2864

**Comment by deep-dark-forest** [comment]
> #330 和这个可以关了
> 然后指定 Minecraft 版本的更新日志的Wiki链接有 Hex-Dragon/PCL2#2864

所以帮助库和启动器库的issue看哪个……

**Comment by deep-dark-forest** [comment]
> #330 和这个可以关了
> 然后指定 Minecraft 版本的更新日志的Wiki链接有 Hex-Dragon/PCL2#2864

好的，已关闭，但是吧我现在是github手机版无法将issue按照not planned关闭……

**Comment by deep-dark-forest** [comment]
不过，我仍然建议保留bwiki的按钮，因为runespace在某些地区还是存在超时现象

**Comment by JingHai-Lingyun** [comment]
好像 bwiki 要被删掉了

**Comment by deep-dark-forest** [comment]
> 好像 bwiki 要被删掉了

好吧那

**Comment by z0z0r4** [comment]
bwiki 已经被删除了，请全域切换到 zh.minecraft.wiki

**Comment by z0z0r4** [comment]
> 不过，我仍然建议保留bwiki的按钮，因为runespace在某些地区还是存在超时现象

有反诈现象（笑
