### ISSUE TITLE
"参与完善PCL帮助"点击报错

### ISSUE THREAD

**Issue by w2w2e2wq** [LTCatt/PCL2Help#344]
![图片](https://github.com/LTCatt/PCL2Help/assets/128943330/a8a24628-87bd-4731-9afe-714e510e31d9)
[Log1.txt](https://github.com/LTCatt/PCL2Help/files/13685986/Log1.txt)

**Comment by WorldHim** [comment]
与 [#2917](https://github.com/Hex-Dragon/PCL2/issues/2917) 重复
