### ISSUE TITLE
图片无法正确加载

### ISSUE THREAD

**Issue by WForst-Breeze** [LTCatt/PCL2Help#346]
Hex-Dragon/PCL2#3188
貌似是 img.z0z0r4.top 的问题

![image](https://github.com/LTCatt/PCL2Help/assets/110760354/48e20cbd-f314-4fdb-b21b-40ed795d7328)

**Comment by allMagicNB** [comment]
@z0z0r4

**Comment by z0z0r4** [comment]
在换备案了，我先切源站看看，等我改下 nginx

**Comment by z0z0r4** [comment]
![ec3ff2bc36f0c2ed2f189c5370472cd1](https://github.com/LTCatt/PCL2Help/assets/78744121/a77f7cf5-e24c-4193-9f01-d7ada3ec93bc)

天才，等我回家换回个人备案，换企业得先解个人

**Comment by z0z0r4** [comment]
Temporary measures
![](https://img.z0z0r4.top/local/2023/08/02/64c9f12712384.png)
