### ISSUE TITLE
最新版2.7.1会被McAfee扫描放入隔离区

### ISSUE THREAD

**Issue by y271727uy** [LTCatt/PCL2Help#359]
rt
下面为具体文件截图
![屏幕截图 2024-04-08 203849](https://github.com/LTCatt/PCL2Help/assets/145999682/b6107cfb-ebcd-4f79-9347-81873832c585)
![屏幕截图 2024-04-08 204007](https://github.com/LTCatt/PCL2Help/assets/145999682/3d73126a-2eb1-4cdb-aec0-5be5fa352ecb)
![屏幕截图 2024-04-07 084255](https://github.com/LTCatt/PCL2Help/assets/145999682/7a07ecda-5f3b-4744-a405-badcecc9e7b8)

**Comment by allMagicNB** [comment]
![d7fe340b34f582f65e9c363857564f78](https://github.com/Hex-Dragon/PCL2/assets/116283787/9cb6bff6-cbfd-4a71-bd58-385c96325725)
哥，这是帮助库，而且报毒的事咱也解决不了，使用 VMProtect 加壳的都会被报毒……

**Comment by LTCatt** [comment]
没救
