### ISSUE TITLE
pcl2无法正确识别java

### ISSUE THREAD

**Issue by Glenavan** [LTCatt/PCL2Help#360]
电脑已安装java8和java17，打开后一直搜索不到java，按手动添加他就会显示正在搜索，我等了半小时也是这样，以下是日志和截图
[Log1.txt](https://github.com/LTCatt/PCL2Help/files/14964933/Log1.txt)
[Log2.txt](https://github.com/LTCatt/PCL2Help/files/14964935/Log2.txt)
[Log3.txt](https://github.com/LTCatt/PCL2Help/files/14964936/Log3.txt)
[Log4.txt](https://github.com/LTCatt/PCL2Help/files/14964937/Log4.txt)
[Log5.txt](https://github.com/LTCatt/PCL2Help/files/14964938/Log5.txt)
![java已安装](https://github.com/LTCatt/PCL2Help/assets/166886247/7adb108f-20e9-4f8b-b784-a8d8958f0117)
![正在搜索](https://github.com/LTCatt/PCL2Help/assets/166886247/3f5b4486-cc45-4aa8-b142-f21b4afb8b1b)
![最新启动器](https://github.com/LTCatt/PCL2Help/assets/166886247/d432f781-67e4-4615-af10-8a0f248ac9cb)

**Comment by allMagicNB** [comment]
哥，这是帮助库，不是你求助的地方

**Comment by LTCatt** [comment]
请前往 https://github.com/Hex-Dragon/PCL2/issues
