### ISSUE TITLE
PCL2与Windows系统·极大不兼容

### ISSUE THREAD

**Issue by klmyjy** [LTCatt/PCL2Help#366]
下载使用PCL2（无论其是否在桌面或是否在独立文件夹内），无论是否将启动器加入Windows系统白名单，都将导致启动器被误删除，附件为删除后在Windows系统进行查询的典型报错
![屏幕截图 2024-05-19 025308](https://github.com/LTCatt/PCL2Help/assets/170201873/c00e80a1-1811-45b7-8bb2-e188e07fa752)

**Comment by LTCatt** [comment]
Hex-Dragon/PCL2#666
