### ISSUE TITLE
https://pcl2-help.gitee.io/ 处于 502 状态

### ISSUE THREAD

**Issue by lihl2011** [LTCatt/PCL2Help#367]
复现位置：更多>帮助>启动器>参与完善 PCL 帮助库>下一步的计划>打开 PCL 帮助站。

会打开 https://pcl2-help.gitee.io/，处于 502 Bad Gateway 状态。

**Comment by allMagicNB** [comment]
这大概率是你自己网络环境问题……

**Comment by allMagicNB** [comment]
所有 Gitee Pages 没法用……

**Comment by LTCatt** [comment]
删掉吧（

**Comment by allMagicNB** [comment]
> 删掉吧（

~~这个小站都不知道废弃多少年了~~
要删记得连脑溢血急救中心里边的也给删掉（
