### ISSUE TITLE
图片炸了

### ISSUE THREAD

**Issue by z0z0r4** [LTCatt/PCL2Help#372]
```
Failed to download the following images:
    https://cdn.newfei.top/image/2023/01/13/ouXw.jpg
    https://cdn.newfei.top/image/2023/01/13/oE4T.jpg
    https://cdn.newfei.top/image/2023/01/13/oPqS.png
    https://cdn.newfei.top/image/2023/01/13/ouXw.jpg
    https://cdn.newfei.top/image/2023/01/13/oE4T.jpg
    https://cdn.newfei.top/image/2023/01/13/oPqS.png
```

**Comment by tangge233** [comment]
爆炸位置：https://github.com/LTCatt/PCL2Help/blob/e86fb4cb2f84cd1915dcc0cf7fcd27cf3f387314/%E5%B8%AE%E5%8A%A9/%E6%8F%90%E4%BA%A4%E5%B8%AE%E5%8A%A9%20-%20VSCode.xaml#L25

一时半会也搞不到原图片，或许要重新弄一遍这个教程的图片？

**Comment by WorldHim** [comment]
<img width="960" alt="1" src="https://github.com/LTCatt/PCL2Help/assets/68632311/429ce520-0c7b-4f2a-b60d-26a8fc327ff6">
<img width="960" alt="2" src="https://github.com/LTCatt/PCL2Help/assets/68632311/7ced606a-0d5a-48ba-b797-15c6868a1fbf">
<img width="960" alt="3" src="https://github.com/LTCatt/PCL2Help/assets/68632311/7e7641da-506c-40a4-80d6-3be2dbd48f46">

**Comment by z0z0r4** [comment]
https://img.z0z0r4.top/local/2024/07/06/6688c37f0629d.png
https://img.z0z0r4.top/local/2024/07/06/6688c37f43af4.png
https://img.z0z0r4.top/local/2024/07/06/6688c37f60b40.png
