### ISSUE TITLE
PCL帮助库内置图床炸了

### ISSUE THREAD

**Issue by Joker2184** [LTCatt/PCL2Help#392]
帮助库 更新mod栏目
打开帮助库图片链接显示无法访问
![497ac26df26e3bae0a9bf157df765f02](https://github.com/user-attachments/assets/462ca060-944f-4e08-9fc4-5a8b0d8012ea)
![96473efadab3d8a7cfb1f3320a4e4ce7](https://github.com/user-attachments/assets/1181284c-861a-4493-bf51-854a01155e25)
![e169058f1b1bb25e5849ce80505d094b](https://github.com/user-attachments/assets/ecd75695-4ac2-45cd-90e7-2addd5bd4396)
![0be30c8d43546f729a16a3d67b90109d](https://github.com/user-attachments/assets/e05d7d80-e4a7-4208-8256-aea0622a97c1)

**Comment by LTCatt** [comment]
已确认 @z0z0r4

**Comment by z0z0r4** [comment]
好像证书掉了...我有 acme 才对啊，明天看看

**Comment by z0z0r4** [comment]
是说我今天还没开口咋回事就好了...我也不知道啥情况

可以关了...不懂

**Comment by Joker2184** [comment]
识别码
FD98-46B5-3CBC-668B

**Comment by allMagicNB** [comment]
> 识别码
> FD98-46B5-3CBC-668B

要给 PCL 本身交反馈才有吧，这里连个 Label 都没有（

**Comment by LTCatt** [comment]
这倒没啥。

你的解锁码：uCMeWqHMS/NR5+vQJTAiUaqvFfi/0a6W
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～
