### ISSUE TITLE
直接用b站的直链

### ISSUE THREAD

**Issue by z0z0r4** [LTCatt/PCL2Help#393]
话说能直接用b站的直链吗...反正启动器没referer

_Originally posted by @z0z0r4 in https://github.com/LTCatt/PCL2Help/issues/392#issuecomment-2376433279_

**Comment by LTCatt** [comment]
会不会根据访问量检查，如果到了一定量就杀了……
毕竟我好像没见过谁用 B 站当图床的，应该有它的原因在吧……
感觉不是很稳妥……

**Comment by z0z0r4** [comment]
要不，我 301 过去试试看，反正随便切回来？或者在内测版试试看之类的，百利无一害...

~~我香港的机子现在纯备用了...都在bangbang的机子上，12月就估计不续了，有点亏~~

**Comment by LTCatt** [comment]
如果炸了那也是损失啊……怎么就百利无一害了……
你想 301 过去试试也可以，能确保炸了可以尽快换回来，不会又得等它炸几天就行（

**Comment by LTCatt** [comment]
新版 MyImage 添加了 FallbackSource 属性，可以用这个安全地上了

**Comment by z0z0r4** [comment]
> 新版 MyImage 添加了 FallbackSource 属性，可以用这个安全地上了

nice…！那我今晚起个 pr

有 example 吗？

**Comment by LTCatt** [comment]
新版的自定义主页教程里有（

**Comment by z0z0r4** [comment]
> 新版的自定义主页教程里有（

出乎意料（x

**Comment by z0z0r4** [comment]
https://socialsisteryi.github.io/bilibili-API-collect/docs/misc/picture.html

**Comment by wuliaodexiaoluo** [comment]
>毕竟我好像没见过谁用 B 站当图床的，应该有它的原因在吧……

萌百的部分图片是加载 BiliBili 的，迄今为止还没看到有 Forbidden 的，除了播放量统计经常被 Forbidden

**Comment by z0z0r4** [comment]
https://github.com/LTCatt/PCL2Help/pull/397

**Comment by z0z0r4** [comment]
机子到期时间：2025年1月7日
说实话很期待到底能不能用...我看看还续费不续费...
