### ISSUE TITLE
PCL.ModMain.HelpEntry..

### ISSUE THREAD

**Issue by WIFIGUN** [LTCatt/PCL2Help#4]
**Screenshots**
![PCL ModMain HelpEntry](https://user-images.githubusercontent.com/70091589/112867108-180baf80-90ed-11eb-9d67-475d1d54dbf9.JPG)

**Code**
`

{
    "__Author__": "WIFIGUN",
	"Title": "NameMC",
	"Description": "Minecraft用戶名/外觀和伺服器查詢",
    "Keywords": [ "skins", "Names", "Servers", "Capes" ],
	"Types": ["参考工具"],
	"IsEvent": true,
	"EventType": "打开网页",
	"EventData": "https://zh-tw.namemc.com"
}
`

**Comment by LTCatt** [comment]
Keywords 为一个字符串，而非数组。
