### ISSUE TITLE
[优化] 使用 VSCode for Web 替代 VSCode?

### ISSUE THREAD

**Issue by shimoranla** [LTCatt/PCL2Help#401]
VSCode 有 [Web 版本](https://vscode.dev)
这个版本不需要安装 Git ，也不会出现通过 https 提交超时等问题
就是拉代码的时候有一定概率抽风（但是刷新两下基本能好）
除了顶部操作被折叠了（不过能提 PR 应该都知道怎么操作）以外其他部分的操作和 VSCode 没太大区别
并且得益于 Azure CDN，境内体验良好（延时:88-488ms，但是能稳定访问）

**Comment by shimoranla** [comment]
Web 版本甚至不需要装插件，自带中文

**Comment by LTCatt** [comment]
还是尽量用大众的作为教程吧……
