### ISSUE TITLE
PCL2待添加的新功能：特定情况下“找回密码”缺少传参

### ISSUE THREAD

**Issue by Kansamu** [LTCatt/PCL2Help#46]
## 在使用PCL2加载Authlib_Injector外置登录时，依然会出现“找回密码”
**如图所示**

![image](https://user-images.githubusercontent.com/70058876/120913721-c9b9f480-c6cb-11eb-8bda-86fca9ce43d7.png)
****
### 方案一
在选择Authlib_Injector登录方式时隐藏此按钮。

### 方案二

> 介于目前使用自建外置方案多为Blessingskin皮肤站，而blessingskin为找回密码提供了永久链接http://www.xxx.com/auth/forgot

所以可以向注册一样，增加传参输入框。供自有服务器站长添加 找回密码

**Comment by LTCatt** [comment]
请在 PCL2 的内置反馈中提交，这里仅限于 PCL2 帮助相关的反馈
