### ISSUE TITLE
显示"hacked client"

### ISSUE THREAD

**Issue by AsterrKat** [LTCatt/PCL2Help#57]
![image](https://user-images.githubusercontent.com/83419978/126057882-9dc0bd37-1163-4604-acec-7071d6ef83ce.png)
![image](https://user-images.githubusercontent.com/83419978/126057894-7438ed61-3e0c-48b8-a96b-9cd7c02ff1f6.png)
正版微软账号登录，经测试只要是原版的都会显示左下角这条信息，并不确定是PCL2有意为之还是mojang的措施。
安装forge或optifine之后就不会有左下角这个消息了
正式版最新版

如果发的地方不合适提前道歉qwq

**Comment by LTCatt** [comment]
https://jinshuju.net/f/rP4b6E
请在这里提交
