### ISSUE TITLE
出现重复帮助内容

### ISSUE THREAD

**Issue by Big-Cake-jpg** [LTCatt/PCL2Help#63]
![52076E28-8F89-4C4C-A663-AE89CF7823EF](https://user-images.githubusercontent.com/76810494/126925429-2ec4ddfa-28e8-49ef-96a1-91b5c14c9ada.jpeg)
如图，经过查看两个帮助内容一致。如果同时属于两个类别，当我没说

**Comment by tangge233** [comment]
没发现重复的帮助啊，是不是看错了...

**Comment by Big-Cake-jpg** [comment]
> 没发现重复的帮助啊，是不是看错了...

刷新了帮助页面，仍然有重复内容
PCL2 版本：Snapshot 2.1.2

**Comment by tangge233** [comment]
似乎并不是重复，在编写之初就规定帮助范围在“Minecraft”和“启动器”之中。

**Comment by Big-Cake-jpg** [comment]
> 似乎并不是重复，在编写之初就规定帮助范围在“Minecraft”和“启动器”之中。

啊这......当我没说
