### ISSUE TITLE
帮助库，备份启动器设置中的备份bat文件已失效

### ISSUE THREAD

**Issue by 6get-xiaofan** [LTCatt/PCL2Help#74]
帮助库，备份启动器设置中的备份bat文件已失效，无法下载。

**Comment by Big-Cake-jpg** [comment]
我这里试了一下，可以啊

**Comment by 6get-xiaofan** [comment]
![image](https://user-images.githubusercontent.com/57002549/130067899-aafee67f-a7b1-4280-925a-4cfd8ec3e749.png)

**Comment by Big-Cake-jpg** [comment]
![c](https://user-images.githubusercontent.com/76810494/130068427-459d5569-83f8-404a-9771-8c939fd830b0.png)

**Comment by 6get-xiaofan** [comment]
建议将空格用下划线代替，此问题非本地问题，错误信息可以看到，这是远程服务器的问题，显示404

**Comment by Big-Cake-jpg** [comment]
我都没用过注册表备份，只是看到你的Issue才试了一下的

**Comment by Big-Cake-jpg** [comment]
我能正常使用

**Comment by Big-Cake-jpg** [comment]
才发现你的帮助界面和我的不一样...你试试把PCL文件夹里的Help文件夹删了？

**Comment by 6get-xiaofan** [comment]
抱歉，好久参与帮助库编写，才发现这些条目太老了😅😅
